project_id = "jjfdvgrujmudscfbjpbn"

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.send-application]
verify_jwt = false